#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace clktick.sv delay.sv delstate.sv f1_fsm.sv lfsr_7.sv mux.sv --top-module delstate --exe delstate_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vdelstate.mk Vdelstate

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vdelstate
echo "\nSimulation completed"

